Repository DAGWorks-Inc/hamilton, pull requests merged in 2024-10, with the labels that each got.

#1104 feat: First-class caching
  .gitignore
  docs/concepts/_caching/view_run_example.svg
  docs/concepts/builder.rst
  docs/concepts/caching.rst
  docs/concepts/index.rst
  docs/conf.py
  docs/how-tos/cache-nodes.rst
  docs/how-tos/caching-tutorial.ipynb
  docs/how-tos/index.rst
  docs/index.md
  docs/reference/caching/caching-logic.rst
  docs/reference/caching/data-versioning.rst
  docs/reference/caching/index.rst
  docs/reference/caching/stores.rst
  examples/caching/README.md
  examples/caching/materializer_tutorial.ipynb
  examples/caching/raw_data.parquet
  examples/caching/requirements.txt
  examples/caching/tutorial.ipynb
  examples/caching_nodes/caching.ipynb
  hamilton/caching/__init__.py
  hamilton/caching/adapter.py
  hamilton/caching/cache_key.py
  hamilton/caching/fingerprinting.py
  hamilton/caching/stores/__init__.py
  hamilton/caching/stores/base.py
  hamilton/caching/stores/file.py
  hamilton/caching/stores/sqlite.py
  hamilton/caching/stores/utils.py
  hamilton/driver.py
  hamilton/experimental/h_cache.py
  hamilton/experimental/h_databackends.py
  hamilton/function_modifiers/__init__.py
  hamilton/function_modifiers/adapters.py
  hamilton/function_modifiers/metadata.py
  hamilton/graph.py
  hamilton/lifecycle/default.py
  hamilton/plugins/h_diskcache.py
  pyproject.toml
  tests/caching/__init__.py
  tests/caching/test_adapter.py
  tests/caching/test_fingerprinting.py
  tests/caching/test_integration.py
  tests/caching/test_metadata_store.py
  tests/caching/test_result_store.py
  tests/function_modifiers/test_adapters.py
  tests/resources/dynamic_parallelism/parallelism_with_caching.py
  tests/test_hamilton_driver.py
Labels: enhancement

#1174 Jupyter Notebook for Data Loaders Example (Data loaders #1122)
  examples/data_loaders/data_loaders.ipynb
Labels: hacktoberfest

#1211 docs: added in-memory caching to reference and concepts sections
  docs/concepts/caching.rst
  docs/reference/caching/stores.rst
Labels: documentation
